export const postConstants={
    POSTING_REQUEST:'POSTING_REQUEST',
    POST_POSTED:'POST_POSTED',
    POSTING_FAILURE:'POSTING_FAILURE',
    FETCHING_POSTS:'FETCHING_POSTS',
    FETCHED_POSTS:'FETCH_POST'
}